# Configuration for https://rust-lang.github.io/rustfmt/

edition = "2024"

use_field_init_shorthand = true

# Unstable options. These require a nightly compiler to use (cargo +nightly fmt).
wrap_comments = true
comment_width = 100
format_code_in_doc_comments = true
normalize_doc_attributes = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
format_macro_matchers = true
